
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 07 14:05:44 GMT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int CHAR = 11;
  public static final int CONCAT = 6;
  public static final int STROKE = 24;
  public static final int INTEGER = 9;
  public static final int GREATER = 47;
  public static final int LCBRACK = 25;
  public static final int LPAREN = 27;
  public static final int RCBRACK = 26;
  public static final int SEMI = 29;
  public static final int REPEAT = 38;
  public static final int LESS = 46;
  public static final int MINUS = 4;
  public static final int RPAREN = 28;
  public static final int NOT = 44;
  public static final int AND = 43;
  public static final int LISTTYPE = 18;
  public static final int TUPLETYPE = 19;
  public static final int TDEF = 51;
  public static final int OR = 42;
  public static final int BOOL = 12;
  public static final int COMMA = 22;
  public static final int UNTIL = 40;
  public static final int PLUS = 2;
  public static final int LESSEQ = 48;
  public static final int IF = 35;
  public static final int ASSIGN = 7;
  public static final int DOT = 21;
  public static final int ID = 13;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int error = 1;
  public static final int NEQ = 50;
  public static final int FDEF = 34;
  public static final int VOID = 33;
  public static final int EQ = 45;
  public static final int LBRACK = 30;
  public static final int TIMES = 3;
  public static final int BOOLTYPE = 20;
  public static final int COLON = 23;
  public static final int ELSE = 36;
  public static final int RBRACK = 31;
  public static final int WHILE = 37;
  public static final int STRINGTYPE = 16;
  public static final int FLOAT = 8;
  public static final int GREATEREQ = 49;
  public static final int LEN = 32;
  public static final int STRING = 10;
  public static final int FLOATTYPE = 14;
  public static final int CHARTYPE = 17;
  public static final int INTEGERTYPE = 15;
  public static final int DO = 41;
}

